services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: frameratr
      POSTGRES_USER: fr_user
      POSTGRES_PASSWORD: fr_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql

  api:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app  # live-reload style dev (optional)

volumes:
  db_data:
